contextvars.patch
rpmvercmp.patch
0002-Hide-known-DeprecationWarning-related-to-PEP-594.patch
0001-Hide-known-DeprecationWarning-related-to-pyOpenSSL.patch
0001-Drop-versioned-dependencies.patch
0002-Drop-Windows-dependencies.patch

